# Generated by Django 5.2.4 on 2025-08-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.DateField(null=True),
        ),
    ]
